### PR TITLE
Implemented API

### PR DESCRIPTION
**Pull request by LiJu09**
Implemented API instead of web scraping

### CODE REVIEW

**Comment by ludeeus** [comment]
This will break all exsisting installations.
There should be instructions in the readme on how to get the key

**Comment by LiJu09** [comment]
Is that enough?

**Comment by LiJu09** [comment]
I will probably close this PR because there is only 100 request per day quota

**Comment by pinkywafer** [comment]
activities has a cost of only 1 unit, so you can make 10,000 requests per day, but from my limited testing, live streams are not returned and as a result these are only listed using once they are "published", ie. after the stream has finished, so sadly this removes functionality also

**Comment by LiJu09** [comment]
For example this https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=1&order=date&channelId=UCDGiCfCZIV5phsoGiPwIcyQ&key=XXX
return `liveBroadcastContent	"live" `
If after stream started is published new video it return `liveBroadcastContent	"none" `
But this return only live streams https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=UCSJ4gkVC6NrvII8umztf0Ow&type=video&eventType=live&key=XXX

**Comment by LiJu09** [comment]
Now it should return live if there is any live stream but url return latest published video

**Comment by LiJu09** [comment]
It can be also as two separate attributes, you can see live stream and if there was video published after stream start you still see that stream but also that published video

**Pull request closed without merging**
